// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Autobots.Infrastracture.LogCenter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Autobots.Infrastracture.LogCenter {

  /// <summary>Holder for reflection information generated from Autobots.Infrastracture.LogCenter.proto</summary>
  public static partial class AutobotsInfrastractureLogCenterReflection {

    #region Descriptor
    /// <summary>File descriptor for Autobots.Infrastracture.LogCenter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AutobotsInfrastractureLogCenterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidBdXRvYm90cy5JbmZyYXN0cmFjdHVyZS5Mb2dDZW50ZXIucHJvdG8SIUF1",
            "dG9ib3RzLkluZnJhc3RyYWN0dXJlLkxvZ0NlbnRlciJACgpMb2dSZXF1ZXN0",
            "Eg8KB21lc3NhZ2UYASABKAkSDwoHbG9jYXRvchgCIAEoCRIQCghvcGVyYXRv",
            "chgDIAEoCSKsAQoLTG9nUmVzcG9uc2USTAoGc3RhdHVzGAEgASgOMjwuQXV0",
            "b2JvdHMuSW5mcmFzdHJhY3R1cmUuTG9nQ2VudGVyLkxvZ1Jlc3BvbnNlLlNl",
            "cnZpbmdTdGF0dXMiTwoNU2VydmluZ1N0YXR1cxILCgdVTktOT1dOEAASCwoH",
            "U0VSVklORxABEg8KC05PVF9TRVJWSU5HEAISEwoPU0VSVklDRV9VTktOT1dO",
            "EAMyzAIKFExvZ1NlcnZpY2VEZWZpbml0aW9uEmUKBEluZm8SLS5BdXRvYm90",
            "cy5JbmZyYXN0cmFjdHVyZS5Mb2dDZW50ZXIuTG9nUmVxdWVzdBouLkF1dG9i",
            "b3RzLkluZnJhc3RyYWN0dXJlLkxvZ0NlbnRlci5Mb2dSZXNwb25zZRJlCgRX",
            "YXJuEi0uQXV0b2JvdHMuSW5mcmFzdHJhY3R1cmUuTG9nQ2VudGVyLkxvZ1Jl",
            "cXVlc3QaLi5BdXRvYm90cy5JbmZyYXN0cmFjdHVyZS5Mb2dDZW50ZXIuTG9n",
            "UmVzcG9uc2USZgoFRXJyb3ISLS5BdXRvYm90cy5JbmZyYXN0cmFjdHVyZS5M",
            "b2dDZW50ZXIuTG9nUmVxdWVzdBouLkF1dG9ib3RzLkluZnJhc3RyYWN0dXJl",
            "LkxvZ0NlbnRlci5Mb2dSZXNwb25zZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Autobots.Infrastracture.LogCenter.LogRequest), global::Autobots.Infrastracture.LogCenter.LogRequest.Parser, new[]{ "Message", "Locator", "Operator" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Autobots.Infrastracture.LogCenter.LogResponse), global::Autobots.Infrastracture.LogCenter.LogResponse.Parser, new[]{ "Status" }, null, new[]{ typeof(global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LogRequest : pb::IMessage<LogRequest> {
    private static readonly pb::MessageParser<LogRequest> _parser = new pb::MessageParser<LogRequest>(() => new LogRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LogRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Autobots.Infrastracture.LogCenter.AutobotsInfrastractureLogCenterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogRequest(LogRequest other) : this() {
      message_ = other.message_;
      locator_ = other.locator_;
      operator_ = other.operator_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogRequest Clone() {
      return new LogRequest(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locator" field.</summary>
    public const int LocatorFieldNumber = 2;
    private string locator_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Locator {
      get { return locator_; }
      set {
        locator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "operator" field.</summary>
    public const int OperatorFieldNumber = 3;
    private string operator_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Operator {
      get { return operator_; }
      set {
        operator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LogRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LogRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (Locator != other.Locator) return false;
      if (Operator != other.Operator) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Locator.Length != 0) hash ^= Locator.GetHashCode();
      if (Operator.Length != 0) hash ^= Operator.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (Locator.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Locator);
      }
      if (Operator.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Operator);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Locator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Locator);
      }
      if (Operator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Operator);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LogRequest other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Locator.Length != 0) {
        Locator = other.Locator;
      }
      if (other.Operator.Length != 0) {
        Operator = other.Operator;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 18: {
            Locator = input.ReadString();
            break;
          }
          case 26: {
            Operator = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LogResponse : pb::IMessage<LogResponse> {
    private static readonly pb::MessageParser<LogResponse> _parser = new pb::MessageParser<LogResponse>(() => new LogResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LogResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Autobots.Infrastracture.LogCenter.AutobotsInfrastractureLogCenterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogResponse(LogResponse other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogResponse Clone() {
      return new LogResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus status_ = global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LogResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LogResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus.Unknown) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LogResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus.Unknown) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Autobots.Infrastracture.LogCenter.LogResponse.Types.ServingStatus) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the LogResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ServingStatus {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("SERVING")] Serving = 1,
        [pbr::OriginalName("NOT_SERVING")] NotServing = 2,
        /// <summary>
        /// Used only by the Watch method.
        /// </summary>
        [pbr::OriginalName("SERVICE_UNKNOWN")] ServiceUnknown = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
