//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebTest.gRPC.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HelloRequest", Namespace="http://microsoft.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class HelloRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="ServiceReference2.SampleWebServiceSoap")]
    public interface SampleWebServiceSoap {
        
        // CODEGEN: 命名空间 http://microsoft.com/webservices/ 的元素名称 hello 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/HelloWorld", ReplyAction="*")]
        MyWebTest.gRPC.ServiceReference2.HelloWorldResponse HelloWorld(MyWebTest.gRPC.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWebTest.gRPC.ServiceReference2.HelloWorldResponse> HelloWorldAsync(MyWebTest.gRPC.ServiceReference2.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://microsoft.com/webservices/ 的元素名称 hello 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/TransTest10kb", ReplyAction="*")]
        MyWebTest.gRPC.ServiceReference2.TransTest10kbResponse TransTest10kb(MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/TransTest10kb", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWebTest.gRPC.ServiceReference2.TransTest10kbResponse> TransTest10kbAsync(MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://microsoft.com/webservices/", Order=0)]
        public MyWebTest.gRPC.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MyWebTest.gRPC.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyWebTest.gRPC.ServiceReference2.HelloRequest hello;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(MyWebTest.gRPC.ServiceReference2.HelloRequest hello) {
            this.hello = hello;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public MyWebTest.gRPC.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MyWebTest.gRPC.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransTest10kbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransTest10kb", Namespace="http://microsoft.com/webservices/", Order=0)]
        public MyWebTest.gRPC.ServiceReference2.TransTest10kbRequestBody Body;
        
        public TransTest10kbRequest() {
        }
        
        public TransTest10kbRequest(MyWebTest.gRPC.ServiceReference2.TransTest10kbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TransTest10kbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyWebTest.gRPC.ServiceReference2.HelloRequest hello;
        
        public TransTest10kbRequestBody() {
        }
        
        public TransTest10kbRequestBody(MyWebTest.gRPC.ServiceReference2.HelloRequest hello) {
            this.hello = hello;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransTest10kbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransTest10kbResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public MyWebTest.gRPC.ServiceReference2.TransTest10kbResponseBody Body;
        
        public TransTest10kbResponse() {
        }
        
        public TransTest10kbResponse(MyWebTest.gRPC.ServiceReference2.TransTest10kbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TransTest10kbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TransTest10kbResult;
        
        public TransTest10kbResponseBody() {
        }
        
        public TransTest10kbResponseBody(string TransTest10kbResult) {
            this.TransTest10kbResult = TransTest10kbResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SampleWebServiceSoapChannel : MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleWebServiceSoapClient : System.ServiceModel.ClientBase<MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap>, MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap {
        
        public SampleWebServiceSoapClient() {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWebTest.gRPC.ServiceReference2.HelloWorldResponse MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap.HelloWorld(MyWebTest.gRPC.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(MyWebTest.gRPC.ServiceReference2.HelloRequest hello) {
            MyWebTest.gRPC.ServiceReference2.HelloWorldRequest inValue = new MyWebTest.gRPC.ServiceReference2.HelloWorldRequest();
            inValue.Body = new MyWebTest.gRPC.ServiceReference2.HelloWorldRequestBody();
            inValue.Body.hello = hello;
            MyWebTest.gRPC.ServiceReference2.HelloWorldResponse retVal = ((MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWebTest.gRPC.ServiceReference2.HelloWorldResponse> MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap.HelloWorldAsync(MyWebTest.gRPC.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWebTest.gRPC.ServiceReference2.HelloWorldResponse> HelloWorldAsync(MyWebTest.gRPC.ServiceReference2.HelloRequest hello) {
            MyWebTest.gRPC.ServiceReference2.HelloWorldRequest inValue = new MyWebTest.gRPC.ServiceReference2.HelloWorldRequest();
            inValue.Body = new MyWebTest.gRPC.ServiceReference2.HelloWorldRequestBody();
            inValue.Body.hello = hello;
            return ((MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWebTest.gRPC.ServiceReference2.TransTest10kbResponse MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap.TransTest10kb(MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest request) {
            return base.Channel.TransTest10kb(request);
        }
        
        public string TransTest10kb(MyWebTest.gRPC.ServiceReference2.HelloRequest hello) {
            MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest inValue = new MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest();
            inValue.Body = new MyWebTest.gRPC.ServiceReference2.TransTest10kbRequestBody();
            inValue.Body.hello = hello;
            MyWebTest.gRPC.ServiceReference2.TransTest10kbResponse retVal = ((MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap)(this)).TransTest10kb(inValue);
            return retVal.Body.TransTest10kbResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWebTest.gRPC.ServiceReference2.TransTest10kbResponse> MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap.TransTest10kbAsync(MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest request) {
            return base.Channel.TransTest10kbAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWebTest.gRPC.ServiceReference2.TransTest10kbResponse> TransTest10kbAsync(MyWebTest.gRPC.ServiceReference2.HelloRequest hello) {
            MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest inValue = new MyWebTest.gRPC.ServiceReference2.TransTest10kbRequest();
            inValue.Body = new MyWebTest.gRPC.ServiceReference2.TransTest10kbRequestBody();
            inValue.Body.hello = hello;
            return ((MyWebTest.gRPC.ServiceReference2.SampleWebServiceSoap)(this)).TransTest10kbAsync(inValue);
        }
    }
}
