//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autobots.InpatientService.LogServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APIResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogServiceReference.LogServiceSoap")]
    public interface LogServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Info", ReplyAction="*")]
        Autobots.InpatientService.LogServiceReference.InfoResponse Info(Autobots.InpatientService.LogServiceReference.InfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Info", ReplyAction="*")]
        System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.InfoResponse> InfoAsync(Autobots.InpatientService.LogServiceReference.InfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Warn", ReplyAction="*")]
        Autobots.InpatientService.LogServiceReference.WarnResponse Warn(Autobots.InpatientService.LogServiceReference.WarnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Warn", ReplyAction="*")]
        System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.WarnResponse> WarnAsync(Autobots.InpatientService.LogServiceReference.WarnRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Error", ReplyAction="*")]
        Autobots.InpatientService.LogServiceReference.ErrorResponse Error(Autobots.InpatientService.LogServiceReference.ErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Error", ReplyAction="*")]
        System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.ErrorResponse> ErrorAsync(Autobots.InpatientService.LogServiceReference.ErrorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Info", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.LogServiceReference.InfoRequestBody Body;
        
        public InfoRequest() {
        }
        
        public InfoRequest(Autobots.InpatientService.LogServiceReference.InfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public InfoRequestBody() {
        }
        
        public InfoRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.LogServiceReference.InfoResponseBody Body;
        
        public InfoResponse() {
        }
        
        public InfoResponse(Autobots.InpatientService.LogServiceReference.InfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Autobots.InpatientService.LogServiceReference.APIResult InfoResult;
        
        public InfoResponseBody() {
        }
        
        public InfoResponseBody(Autobots.InpatientService.LogServiceReference.APIResult InfoResult) {
            this.InfoResult = InfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WarnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Warn", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.LogServiceReference.WarnRequestBody Body;
        
        public WarnRequest() {
        }
        
        public WarnRequest(Autobots.InpatientService.LogServiceReference.WarnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WarnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public WarnRequestBody() {
        }
        
        public WarnRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WarnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WarnResponse", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.LogServiceReference.WarnResponseBody Body;
        
        public WarnResponse() {
        }
        
        public WarnResponse(Autobots.InpatientService.LogServiceReference.WarnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WarnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Autobots.InpatientService.LogServiceReference.APIResult WarnResult;
        
        public WarnResponseBody() {
        }
        
        public WarnResponseBody(Autobots.InpatientService.LogServiceReference.APIResult WarnResult) {
            this.WarnResult = WarnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Error", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.LogServiceReference.ErrorRequestBody Body;
        
        public ErrorRequest() {
        }
        
        public ErrorRequest(Autobots.InpatientService.LogServiceReference.ErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public ErrorRequestBody() {
        }
        
        public ErrorRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ErrorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.LogServiceReference.ErrorResponseBody Body;
        
        public ErrorResponse() {
        }
        
        public ErrorResponse(Autobots.InpatientService.LogServiceReference.ErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Autobots.InpatientService.LogServiceReference.APIResult ErrorResult;
        
        public ErrorResponseBody() {
        }
        
        public ErrorResponseBody(Autobots.InpatientService.LogServiceReference.APIResult ErrorResult) {
            this.ErrorResult = ErrorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogServiceSoapChannel : Autobots.InpatientService.LogServiceReference.LogServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogServiceSoapClient : System.ServiceModel.ClientBase<Autobots.InpatientService.LogServiceReference.LogServiceSoap>, Autobots.InpatientService.LogServiceReference.LogServiceSoap {
        
        public LogServiceSoapClient() {
        }
        
        public LogServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autobots.InpatientService.LogServiceReference.InfoResponse Autobots.InpatientService.LogServiceReference.LogServiceSoap.Info(Autobots.InpatientService.LogServiceReference.InfoRequest request) {
            return base.Channel.Info(request);
        }
        
        public Autobots.InpatientService.LogServiceReference.APIResult Info(string message) {
            Autobots.InpatientService.LogServiceReference.InfoRequest inValue = new Autobots.InpatientService.LogServiceReference.InfoRequest();
            inValue.Body = new Autobots.InpatientService.LogServiceReference.InfoRequestBody();
            inValue.Body.message = message;
            Autobots.InpatientService.LogServiceReference.InfoResponse retVal = ((Autobots.InpatientService.LogServiceReference.LogServiceSoap)(this)).Info(inValue);
            return retVal.Body.InfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.InfoResponse> Autobots.InpatientService.LogServiceReference.LogServiceSoap.InfoAsync(Autobots.InpatientService.LogServiceReference.InfoRequest request) {
            return base.Channel.InfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.InfoResponse> InfoAsync(string message) {
            Autobots.InpatientService.LogServiceReference.InfoRequest inValue = new Autobots.InpatientService.LogServiceReference.InfoRequest();
            inValue.Body = new Autobots.InpatientService.LogServiceReference.InfoRequestBody();
            inValue.Body.message = message;
            return ((Autobots.InpatientService.LogServiceReference.LogServiceSoap)(this)).InfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autobots.InpatientService.LogServiceReference.WarnResponse Autobots.InpatientService.LogServiceReference.LogServiceSoap.Warn(Autobots.InpatientService.LogServiceReference.WarnRequest request) {
            return base.Channel.Warn(request);
        }
        
        public Autobots.InpatientService.LogServiceReference.APIResult Warn(string message) {
            Autobots.InpatientService.LogServiceReference.WarnRequest inValue = new Autobots.InpatientService.LogServiceReference.WarnRequest();
            inValue.Body = new Autobots.InpatientService.LogServiceReference.WarnRequestBody();
            inValue.Body.message = message;
            Autobots.InpatientService.LogServiceReference.WarnResponse retVal = ((Autobots.InpatientService.LogServiceReference.LogServiceSoap)(this)).Warn(inValue);
            return retVal.Body.WarnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.WarnResponse> Autobots.InpatientService.LogServiceReference.LogServiceSoap.WarnAsync(Autobots.InpatientService.LogServiceReference.WarnRequest request) {
            return base.Channel.WarnAsync(request);
        }
        
        public System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.WarnResponse> WarnAsync(string message) {
            Autobots.InpatientService.LogServiceReference.WarnRequest inValue = new Autobots.InpatientService.LogServiceReference.WarnRequest();
            inValue.Body = new Autobots.InpatientService.LogServiceReference.WarnRequestBody();
            inValue.Body.message = message;
            return ((Autobots.InpatientService.LogServiceReference.LogServiceSoap)(this)).WarnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autobots.InpatientService.LogServiceReference.ErrorResponse Autobots.InpatientService.LogServiceReference.LogServiceSoap.Error(Autobots.InpatientService.LogServiceReference.ErrorRequest request) {
            return base.Channel.Error(request);
        }
        
        public Autobots.InpatientService.LogServiceReference.APIResult Error(string message) {
            Autobots.InpatientService.LogServiceReference.ErrorRequest inValue = new Autobots.InpatientService.LogServiceReference.ErrorRequest();
            inValue.Body = new Autobots.InpatientService.LogServiceReference.ErrorRequestBody();
            inValue.Body.message = message;
            Autobots.InpatientService.LogServiceReference.ErrorResponse retVal = ((Autobots.InpatientService.LogServiceReference.LogServiceSoap)(this)).Error(inValue);
            return retVal.Body.ErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.ErrorResponse> Autobots.InpatientService.LogServiceReference.LogServiceSoap.ErrorAsync(Autobots.InpatientService.LogServiceReference.ErrorRequest request) {
            return base.Channel.ErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Autobots.InpatientService.LogServiceReference.ErrorResponse> ErrorAsync(string message) {
            Autobots.InpatientService.LogServiceReference.ErrorRequest inValue = new Autobots.InpatientService.LogServiceReference.ErrorRequest();
            inValue.Body = new Autobots.InpatientService.LogServiceReference.ErrorRequestBody();
            inValue.Body.message = message;
            return ((Autobots.InpatientService.LogServiceReference.LogServiceSoap)(this)).ErrorAsync(inValue);
        }
    }
}
