//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autobots.InpatientService.FileServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Autobots.InpatientService.FileServiceReference.APIResultOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Autobots.InpatientService.FileServiceReference.APIResultOfBoolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Autobots.InpatientService.FileServiceReference.APIResultOfArrayOfByte))]
    public partial class APIResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResultOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APIResultOfString : Autobots.InpatientService.FileServiceReference.APIResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResultOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APIResultOfBoolean : Autobots.InpatientService.FileServiceReference.APIResult {
        
        private bool DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResultOfArrayOfByte", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class APIResultOfArrayOfByte : Autobots.InpatientService.FileServiceReference.APIResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServiceReference.FileServiceSoap")]
    public interface FileServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllBytes", ReplyAction="*")]
        Autobots.InpatientService.FileServiceReference.ReadAllBytesResponse ReadAllBytes(Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.ReadAllBytesResponse> ReadAllBytesAsync(Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTexts", ReplyAction="*")]
        Autobots.InpatientService.FileServiceReference.ReadAllTextsResponse ReadAllTexts(Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAllTexts", ReplyAction="*")]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.ReadAllTextsResponse> ReadAllTextsAsync(Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteAllBytes", ReplyAction="*")]
        Autobots.InpatientService.FileServiceReference.WriteAllBytesResponse WriteAllBytes(Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteAllBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.WriteAllBytesResponse> WriteAllBytesAsync(Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteAllTexts", ReplyAction="*")]
        Autobots.InpatientService.FileServiceReference.WriteAllTextsResponse WriteAllTexts(Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteAllTexts", ReplyAction="*")]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.WriteAllTextsResponse> WriteAllTextsAsync(Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllBytes", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.ReadAllBytesRequestBody Body;
        
        public ReadAllBytesRequest() {
        }
        
        public ReadAllBytesRequest(Autobots.InpatientService.FileServiceReference.ReadAllBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ReadAllBytesRequestBody() {
        }
        
        public ReadAllBytesRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.ReadAllBytesResponseBody Body;
        
        public ReadAllBytesResponse() {
        }
        
        public ReadAllBytesResponse(Autobots.InpatientService.FileServiceReference.ReadAllBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Autobots.InpatientService.FileServiceReference.APIResultOfArrayOfByte ReadAllBytesResult;
        
        public ReadAllBytesResponseBody() {
        }
        
        public ReadAllBytesResponseBody(Autobots.InpatientService.FileServiceReference.APIResultOfArrayOfByte ReadAllBytesResult) {
            this.ReadAllBytesResult = ReadAllBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllTextsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllTexts", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.ReadAllTextsRequestBody Body;
        
        public ReadAllTextsRequest() {
        }
        
        public ReadAllTextsRequest(Autobots.InpatientService.FileServiceReference.ReadAllTextsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllTextsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ReadAllTextsRequestBody() {
        }
        
        public ReadAllTextsRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllTextsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllTextsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.ReadAllTextsResponseBody Body;
        
        public ReadAllTextsResponse() {
        }
        
        public ReadAllTextsResponse(Autobots.InpatientService.FileServiceReference.ReadAllTextsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllTextsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Autobots.InpatientService.FileServiceReference.APIResultOfString ReadAllTextsResult;
        
        public ReadAllTextsResponseBody() {
        }
        
        public ReadAllTextsResponseBody(Autobots.InpatientService.FileServiceReference.APIResultOfString ReadAllTextsResult) {
            this.ReadAllTextsResult = ReadAllTextsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteAllBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteAllBytes", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.WriteAllBytesRequestBody Body;
        
        public WriteAllBytesRequest() {
        }
        
        public WriteAllBytesRequest(Autobots.InpatientService.FileServiceReference.WriteAllBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteAllBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] bytes;
        
        public WriteAllBytesRequestBody() {
        }
        
        public WriteAllBytesRequestBody(string fileName, byte[] bytes) {
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteAllBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteAllBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.WriteAllBytesResponseBody Body;
        
        public WriteAllBytesResponse() {
        }
        
        public WriteAllBytesResponse(Autobots.InpatientService.FileServiceReference.WriteAllBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteAllBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Autobots.InpatientService.FileServiceReference.APIResultOfBoolean WriteAllBytesResult;
        
        public WriteAllBytesResponseBody() {
        }
        
        public WriteAllBytesResponseBody(Autobots.InpatientService.FileServiceReference.APIResultOfBoolean WriteAllBytesResult) {
            this.WriteAllBytesResult = WriteAllBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteAllTextsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteAllTexts", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.WriteAllTextsRequestBody Body;
        
        public WriteAllTextsRequest() {
        }
        
        public WriteAllTextsRequest(Autobots.InpatientService.FileServiceReference.WriteAllTextsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteAllTextsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string texts;
        
        public WriteAllTextsRequestBody() {
        }
        
        public WriteAllTextsRequestBody(string fileName, string texts) {
            this.fileName = fileName;
            this.texts = texts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteAllTextsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteAllTextsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Autobots.InpatientService.FileServiceReference.WriteAllTextsResponseBody Body;
        
        public WriteAllTextsResponse() {
        }
        
        public WriteAllTextsResponse(Autobots.InpatientService.FileServiceReference.WriteAllTextsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteAllTextsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Autobots.InpatientService.FileServiceReference.APIResultOfBoolean WriteAllTextsResult;
        
        public WriteAllTextsResponseBody() {
        }
        
        public WriteAllTextsResponseBody(Autobots.InpatientService.FileServiceReference.APIResultOfBoolean WriteAllTextsResult) {
            this.WriteAllTextsResult = WriteAllTextsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileServiceSoapChannel : Autobots.InpatientService.FileServiceReference.FileServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceSoapClient : System.ServiceModel.ClientBase<Autobots.InpatientService.FileServiceReference.FileServiceSoap>, Autobots.InpatientService.FileServiceReference.FileServiceSoap {
        
        public FileServiceSoapClient() {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autobots.InpatientService.FileServiceReference.ReadAllBytesResponse Autobots.InpatientService.FileServiceReference.FileServiceSoap.ReadAllBytes(Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest request) {
            return base.Channel.ReadAllBytes(request);
        }
        
        public Autobots.InpatientService.FileServiceReference.APIResultOfArrayOfByte ReadAllBytes(string fileName) {
            Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest inValue = new Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.ReadAllBytesRequestBody();
            inValue.Body.fileName = fileName;
            Autobots.InpatientService.FileServiceReference.ReadAllBytesResponse retVal = ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).ReadAllBytes(inValue);
            return retVal.Body.ReadAllBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.ReadAllBytesResponse> Autobots.InpatientService.FileServiceReference.FileServiceSoap.ReadAllBytesAsync(Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest request) {
            return base.Channel.ReadAllBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.ReadAllBytesResponse> ReadAllBytesAsync(string fileName) {
            Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest inValue = new Autobots.InpatientService.FileServiceReference.ReadAllBytesRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.ReadAllBytesRequestBody();
            inValue.Body.fileName = fileName;
            return ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).ReadAllBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autobots.InpatientService.FileServiceReference.ReadAllTextsResponse Autobots.InpatientService.FileServiceReference.FileServiceSoap.ReadAllTexts(Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest request) {
            return base.Channel.ReadAllTexts(request);
        }
        
        public Autobots.InpatientService.FileServiceReference.APIResultOfString ReadAllTexts(string fileName) {
            Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest inValue = new Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.ReadAllTextsRequestBody();
            inValue.Body.fileName = fileName;
            Autobots.InpatientService.FileServiceReference.ReadAllTextsResponse retVal = ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).ReadAllTexts(inValue);
            return retVal.Body.ReadAllTextsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.ReadAllTextsResponse> Autobots.InpatientService.FileServiceReference.FileServiceSoap.ReadAllTextsAsync(Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest request) {
            return base.Channel.ReadAllTextsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.ReadAllTextsResponse> ReadAllTextsAsync(string fileName) {
            Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest inValue = new Autobots.InpatientService.FileServiceReference.ReadAllTextsRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.ReadAllTextsRequestBody();
            inValue.Body.fileName = fileName;
            return ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).ReadAllTextsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autobots.InpatientService.FileServiceReference.WriteAllBytesResponse Autobots.InpatientService.FileServiceReference.FileServiceSoap.WriteAllBytes(Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest request) {
            return base.Channel.WriteAllBytes(request);
        }
        
        public Autobots.InpatientService.FileServiceReference.APIResultOfBoolean WriteAllBytes(string fileName, byte[] bytes) {
            Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest inValue = new Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.WriteAllBytesRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            Autobots.InpatientService.FileServiceReference.WriteAllBytesResponse retVal = ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).WriteAllBytes(inValue);
            return retVal.Body.WriteAllBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.WriteAllBytesResponse> Autobots.InpatientService.FileServiceReference.FileServiceSoap.WriteAllBytesAsync(Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest request) {
            return base.Channel.WriteAllBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.WriteAllBytesResponse> WriteAllBytesAsync(string fileName, byte[] bytes) {
            Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest inValue = new Autobots.InpatientService.FileServiceReference.WriteAllBytesRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.WriteAllBytesRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            return ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).WriteAllBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autobots.InpatientService.FileServiceReference.WriteAllTextsResponse Autobots.InpatientService.FileServiceReference.FileServiceSoap.WriteAllTexts(Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest request) {
            return base.Channel.WriteAllTexts(request);
        }
        
        public Autobots.InpatientService.FileServiceReference.APIResultOfBoolean WriteAllTexts(string fileName, string texts) {
            Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest inValue = new Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.WriteAllTextsRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.texts = texts;
            Autobots.InpatientService.FileServiceReference.WriteAllTextsResponse retVal = ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).WriteAllTexts(inValue);
            return retVal.Body.WriteAllTextsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.WriteAllTextsResponse> Autobots.InpatientService.FileServiceReference.FileServiceSoap.WriteAllTextsAsync(Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest request) {
            return base.Channel.WriteAllTextsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Autobots.InpatientService.FileServiceReference.WriteAllTextsResponse> WriteAllTextsAsync(string fileName, string texts) {
            Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest inValue = new Autobots.InpatientService.FileServiceReference.WriteAllTextsRequest();
            inValue.Body = new Autobots.InpatientService.FileServiceReference.WriteAllTextsRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.texts = texts;
            return ((Autobots.InpatientService.FileServiceReference.FileServiceSoap)(this)).WriteAllTextsAsync(inValue);
        }
    }
}
