// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Autobots.Infrastracture.LogCenter.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Autobots.Infrastracture.LogCenter {
  public static partial class LogServiceDefinition
  {
    static readonly string __ServiceName = "Autobots.Infrastracture.LogCenter.LogServiceDefinition";

    static readonly grpc::Marshaller<global::Autobots.Infrastracture.LogCenter.LogRequest> __Marshaller_Autobots_Infrastracture_LogCenter_LogRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Autobots.Infrastracture.LogCenter.LogRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Autobots.Infrastracture.LogCenter.LogResponse> __Marshaller_Autobots_Infrastracture_LogCenter_LogResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Autobots.Infrastracture.LogCenter.LogResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse> __Method_Info = new grpc::Method<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Info",
        __Marshaller_Autobots_Infrastracture_LogCenter_LogRequest,
        __Marshaller_Autobots_Infrastracture_LogCenter_LogResponse);

    static readonly grpc::Method<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse> __Method_Warn = new grpc::Method<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Warn",
        __Marshaller_Autobots_Infrastracture_LogCenter_LogRequest,
        __Marshaller_Autobots_Infrastracture_LogCenter_LogResponse);

    static readonly grpc::Method<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse> __Method_Error = new grpc::Method<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Error",
        __Marshaller_Autobots_Infrastracture_LogCenter_LogRequest,
        __Marshaller_Autobots_Infrastracture_LogCenter_LogResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Autobots.Infrastracture.LogCenter.AutobotsInfrastractureLogCenterReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LogServiceDefinition</summary>
    [grpc::BindServiceMethod(typeof(LogServiceDefinition), "BindService")]
    public abstract partial class LogServiceDefinitionBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Autobots.Infrastracture.LogCenter.LogResponse> Info(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Autobots.Infrastracture.LogCenter.LogResponse> Warn(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Autobots.Infrastracture.LogCenter.LogResponse> Error(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LogServiceDefinition</summary>
    public partial class LogServiceDefinitionClient : grpc::ClientBase<LogServiceDefinitionClient>
    {
      /// <summary>Creates a new client for LogServiceDefinition</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LogServiceDefinitionClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LogServiceDefinition that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LogServiceDefinitionClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LogServiceDefinitionClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LogServiceDefinitionClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Autobots.Infrastracture.LogCenter.LogResponse Info(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Info(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Autobots.Infrastracture.LogCenter.LogResponse Info(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Info, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Autobots.Infrastracture.LogCenter.LogResponse> InfoAsync(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Autobots.Infrastracture.LogCenter.LogResponse> InfoAsync(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Info, null, options, request);
      }
      public virtual global::Autobots.Infrastracture.LogCenter.LogResponse Warn(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Warn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Autobots.Infrastracture.LogCenter.LogResponse Warn(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Warn, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Autobots.Infrastracture.LogCenter.LogResponse> WarnAsync(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WarnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Autobots.Infrastracture.LogCenter.LogResponse> WarnAsync(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Warn, null, options, request);
      }
      public virtual global::Autobots.Infrastracture.LogCenter.LogResponse Error(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Error(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Autobots.Infrastracture.LogCenter.LogResponse Error(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Error, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Autobots.Infrastracture.LogCenter.LogResponse> ErrorAsync(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ErrorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Autobots.Infrastracture.LogCenter.LogResponse> ErrorAsync(global::Autobots.Infrastracture.LogCenter.LogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Error, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LogServiceDefinitionClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LogServiceDefinitionClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LogServiceDefinitionBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Info, serviceImpl.Info)
          .AddMethod(__Method_Warn, serviceImpl.Warn)
          .AddMethod(__Method_Error, serviceImpl.Error).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LogServiceDefinitionBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Info, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse>(serviceImpl.Info));
      serviceBinder.AddMethod(__Method_Warn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse>(serviceImpl.Warn));
      serviceBinder.AddMethod(__Method_Error, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Autobots.Infrastracture.LogCenter.LogRequest, global::Autobots.Infrastracture.LogCenter.LogResponse>(serviceImpl.Error));
    }

  }
}
#endregion
